language: cpp

compiler:
  - clang
  - gcc

env:
  - CTEST_OUTPUT_ON_FAILURE=1

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
# install json-c
  - sudo apt-get install build-essential
  - sudo apt-get install wget
  - sudo apt-get install libtool
  - git clone -b json-c-0.12 https://github.com/json-c/json-c
  - cd json-c
  - sh autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd ..
  - sudo apt-get install -y libmicrohttpd-dev 

script:
  - cmake . && make && make test

